

-- no pude exportar mi bd desde oracle debido a eso adjunto script de las tablas que cree 
-- para utilizar en el proyecto
CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY, -- Columna de identificación única autogenerada
    nombre VARCHAR2(100) NOT NULL,             -- Nombre del producto (no puede ser nulo)
    precio NUMBER(10, 2),                      -- Precio del producto (número con 2 decimales)
    codigo VARCHAR2(20) UNIQUE,                -- Código del producto (único)
    PRIMARY KEY (id)                           -- Definir la columna id como clave primaria
);


  CREATE TABLE clientes (
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(100)  NOT NULL,
    apellido VARCHAR2(100),
    direccion VARCHAR2(200),
    ciudad VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    cedula VARCHAR2(20) UNIQUE,-- la cedula ni el ruc no pueden repetirse
    ruc VARCHAR2(20) UNIQUE
);

  

CREATE TABLE venta_cabecera (
    id NUMBER PRIMARY KEY,
    fecha DATE,
    cliente_id NUMBER,
    documento_tipo VARCHAR2(20),
    documento_numero VARCHAR2(50),
    monto_total NUMBER,
    iva_total NUMBER,
    timbrado VARCHAR2(50),
    CONSTRAINT uk_timbrado_documento UNIQUE (timbrado, documento_numero), -- Restricción UNIQUE para timbrado 
  --y número de documento esto para que no se genere una factura del mismo numero y timbrado
    FOREIGN KEY (cliente_id) REFERENCES clientes(id)-- esta relacionado al cliente
);

CREATE TABLE venta_detalle (
    id NUMBER PRIMARY KEY,
    venta_id NUMBER,
    producto_id NUMBER,
    cantidad NUMBER,
    precio_unitario NUMBER,
    monto_subtotal NUMBER,
    monto_iva NUMBER,
    monto_total NUMBER,
    FOREIGN KEY (venta_id) REFERENCES venta_cabecera(id),-- id con venta cabecera para que no se inserte un detalle sin cabecera
    FOREIGN KEY (producto_id) REFERENCES productos(id)-- se relaciona directamente con producto
);


